library(edgeR)
library(tidyverse)

# -- Setup paths
## Inputs - Those were generated by the JBC
TX2_CTS <- here("../Internal_Datasets/Gavrila Lab Bulk RNAseq Data/tx2gene_counts.rds")
CPM_CSV <- here("../Internal_Datasets/Gavrila Lab Bulk RNAseq Data/logCPM_for_plotting.csv")

## Outputs
LOG_CPM_CSV <- here("./output/3.heat_signature/3.public_bulkrnaseq/data/logCPM_for_correlations.csv")

#Load the counts from JBC analysis
salej_counts <- readRDS(TX2_CTS)

#Confirm these are counts
head(salej_counts)
summary(salej_counts)
colSums(salej_counts)


# Step 1: Read your counts
counts <- salej_counts  # already loaded

# Step 2: Make DGEList object
dge <- DGEList(counts = counts)

# Step 3: Compute CPM
cpm_matrix <- cpm(dge, log = FALSE)  # raw CPMs

# Step 4: Log-transform CPMs
log2_cpm <- log2(cpm_matrix + 1)  # safe transformation for zeros

cpm_data <- read.csv(CPM_CSV)

cpm_data <- cpm_data %>% select(X, gene)
log2_cpm <- as.data.frame(log2_cpm) %>% rownames_to_column("X")

final_data <- cpm_data %>% left_join(log2_cpm, by = "X")

write.csv(final_data, LOG_CPM_CSV)
