#!/bin/bash
set -euo pipefail

# Purpose:
# Run COMPASS on the MEBOCOST-derived average expression matrix generated by
# the multisample neck adipose workflow.
#
# Workflow:
# 1. MEBOCOST notebook exports avg_exp_mat_multi.tsv
# 2. This script runs COMPASS on that matrix
# 3. MEBOCOST notebook re-imports the COMPASS output directory to constrain
#    communication results and generate downstream tables for R analysis

# -------------------------------------------------------------------------
# Define inputs, outputs, and runtime settings
# -------------------------------------------------------------------------

# Adjust this path to your project root directory
PROJECT_ROOT="~/Projects/Camara_2025_snRNAseq/NeckAdipose"

# Optional shared paths for consistency with the MEBOCOST workflow
INPUT_H5AD="${PROJECT_ROOT}/data/adata_integrated_soupXoutput_with_infer_forR_temp_Dec18_cleaned.h5ad"
CONFIG_PATH="${PROJECT_ROOT}/scripts/mebocost/mebocost.conf"

# Output directories
MEBO_OUTPUT_DIR="${PROJECT_ROOT}/output/4.downstream_pipelines/mebocost/data"
COMPASS_OUTPUT_DIR="${PROJECT_ROOT}/output/4.downstream_pipelines/compass/data"
COMPASS_OUTPUT_PATH="${COMPASS_OUTPUT_DIR}/compass_res_multi_Deep_Sup"
COMPASS_TEMP_PATH="${COMPASS_OUTPUT_DIR}/compass_res_tmp_multi_Deep_Sup"

# Average expression matrix exported from the MEBOCOST notebook
EXPR_TSV_PATH="${MEBO_OUTPUT_DIR}/avg_exp_mat_multi.tsv"

# Species setting expected by COMPASS
SPECIES="homo_sapiens"

# Number of CPU threads to use
CORES=8

# Path to the COMPASS executable inside the analysis environment
COMPASS_BIN="/opt/miniconda3/envs/mebocost/bin/compass"

# -------------------------------------------------------------------------
# Check required inputs
# -------------------------------------------------------------------------
if [[ ! -f "$EXPR_TSV_PATH" ]]; then
  echo "ERROR: Input expression matrix not found: $EXPR_TSV_PATH" >&2
  exit 1
fi

if [[ ! -x "$COMPASS_BIN" ]]; then
  echo "ERROR: COMPASS executable not found or not executable: $COMPASS_BIN" >&2
  exit 1
fi

# -------------------------------------------------------------------------
# Create output directories
# -------------------------------------------------------------------------
mkdir -p "$MEBO_OUTPUT_DIR"
mkdir -p "$(dirname "$COMPASS_OUTPUT_PATH")"
mkdir -p "$(dirname "$COMPASS_TEMP_PATH")"

# -------------------------------------------------------------------------
# Run COMPASS
# -------------------------------------------------------------------------
echo "++++ Running COMPASS on multisample neck adipose matrix"
echo "Input matrix: $EXPR_TSV_PATH"
echo "Output dir:   $COMPASS_OUTPUT_PATH"
echo "Temp dir:     $COMPASS_TEMP_PATH"

"$COMPASS_BIN" \
  --data "$EXPR_TSV_PATH" \
  --num-thread "$CORES" \
  --species "$SPECIES" \
  --output-dir "$COMPASS_OUTPUT_PATH" \
  --temp-dir "$COMPASS_TEMP_PATH" \
  --calc-metabolites \
  --lambda 0

echo "++++ COMPASS finished successfully"